name:  "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install yarn packages
        run: |
          yarn install --pure-lockfile
      - name: Install bundler
        run: |
          gem install bundler
      - name: Install gems
        run: |
          bundle install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} 
          RAILS_ENV: test
        run: |
          bundle exec rails test:all
      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
